nameOverride: can-docker-dwh-memcache-service
fullnameOverride: ""
namespace:
  name: can-docker-dwh-memcache-service
environment: staging
replicaCount: 0
timeToFinishWork: 3600
iam:
  role: arn:aws:iam::543777179833:role/eks-staging-can-{{ .Values.nameOverride }}-staging
service:
  type: ClusterIP
  port: 9240
  health_port: 9241
image:
  repository: 543777179833.dkr.ecr.eu-west-1.amazonaws.com/can-docker-dwh-memcache-service
  tag: 1.0.0.378
  pullPolicy: Always
deployment:
  reloader: "true"
env:
  secrets:
    - name: CAN_SERVICE_DWH_REDIS_PASSWORD
      refname: '{{ .Release.Name }}'
      refkey: redis_password
  variables:
    - name: JAVA_OPTS
      value: -Xmx300m -Xms64m -XX:MaxMetaspaceSize=120m
volumeMounts:
  - mountPath: /etc/can/application.yml
    name: '{{ .Values.nameOverride }}'
    subPath: application.yml
  - mountPath: /etc/can/application.properties
    name: '{{ .Values.nameOverride }}'
    subPath: application.properties
  - mountPath: /etc/can/logback.xml
    name: '{{ .Values.nameOverride }}'
    subPath: logback.xml
resources:
  limits:
    cpu: 500m
    memory: 640Mi
  requests:
    cpu: 10m
    memory: 512Mi
nodeSelector: {}
tolerations: []
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
                - '{{ .Release.Name }}'
        topologyKey: kubernetes.io/hostname
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  paths:
    - /rest/projects/([a-z0-9]{16})/dwh/(.*)
  hosts:
    - staging.cleveranalytics.com
  tls: []
applicationProperties:
  #######################################
  ### Application specific properties ###
  #######################################
  service.name: DwhMemcacheService
  can.mvc.maxPageSize: 20000
  ### AWS ###
  can.service:
    aws:
      accountId: "543777179833"
      region: eu-west-1
    dwh.memcache.aws:
      sqs:
        queryQueue: queries-staging-ttestt.fifo
      s3:
        offloadBucket: can-dwh-sqs-offload-staging
      dynamodb:
        cacheTable: staging-dwh-cache-service-ttestt
  # TODO: remove when CAN-13200 is released and deployed on production (BEGIN)
  ### AWS SQS ###
  can.service.dwh.sqs.region: eu-west-1
  can.service.dwh.sqs.queryQueue: queries-staging-st8kwe.fifo
  can.service.dwh.sqs.concurrency: 3-10
  # NOTE: following properties are relevant only when NOT running in profile aws-sqs-iam-role-grant (does not apply for staging/production deployment)
  #can.service.dwh.sqs.accessKey: AKIAX5G5FJC4Q6WD5MRN
  #can.service.dwh.sqs.secretKey: SECRET

  ### AWS S3 ###
  can.service.dwh.memcache.bucket: can-dwh-sqs-offload-staging
  can.service.dwh.memcache.bucket.region: eu-west-1
  # NOTE: following properties are relevant only when NOT running in profile aws-s3-iam-role-grant (does not apply for staging/production deployment)
  #can.service.dwh.memcache.s3.accessKey: AKIAX5G5FJC4Q6WD5MRN
  #can.service.dwh.memcache.s3.secretKey: SECRET

  ### DynamoDB Stream configuration (active only with profile: aws-dynamodb) ###
  can.service.dwh.cache.dynamodb.region: eu-west-1
  can.service.dwh.cache.dynamodb.table: dwh-cache-staging
  # NOTE: following properties are relevant only when running in profile aws-dynamodb-credentials (does not apply for staging/production deployment)
  #can.service.dwh.cache.dynamodb.accessKey: AKIAX5G5FJC4Q6WD5MRN
  #can.service.dwh.cache.dynamodb.secretKey: SECRET
  # TODO: remove when CAN-13200 is released and deployed on production (END)

  ### Redis ###
  can.service.dwh.redis.hostname: localhost
  can.service.dwh.redis.port: 6379
  can.service.dwh.redis.password:
  can.service.dwh.redis.pool.minIdle: 10
  can.service.dwh.redis.pool.maxTotal: 50
  can.service.dwh.redis.pool.maxWaitMillis: 5000
  can.service.dwh.redis.pool.testWhileIdle: true
  can.service.dwh.redis.connectTimeoutSeconds: 5
  can.service.dwh.redis.readTimeoutSeconds: 5
  # when editing, do not forget to change the dialect in JUnit test manually
  can.service.dwh.sqldialect: POSTGRES_9_5
  # correct DWH cluster id is assigned during deployment
  can.service.dwh.dwhClusterId: ttestt
  ### other microservices ###
  can.service.project.serverUrl: https://staging.clevermaps.io:443
  can.service.md.serverUrl: https://staging.clevermaps.io:443
  ##############################
  ### Spring core properties ###
  ##############################
  spring.profiles.active: dev
  #spring.profiles.active: dev, aws-credentials, aws-dynamodb
  #spring.profiles.active: aws-iam-role-grant, aws-dynamodb

  ### from application-common.yml ###
  spring.lifecycle.timeout-per-shutdown-phase: 60s
  ###########################
  ### Actuator properties ###
  ###########################
  management.server.port: 9241
  management.endpoint.health.group.readiness.include: dynamoDb,jms,redis
  ### from application-common.yml ###
  management.server.add-application-context-header: false
  management.endpoint.metrics.enabled: true
  management.endpoint.prometheus.enabled: true
  management.endpoints.web.exposure.include: health,info,metrics,prometheus
  management.metrics.export.prometheus.enabled: true
  management.endpoint.health.show-details: always
  management.endpoint.health.probes.enabled: true
  management.endpoint.health.group.liveness.include: diskSpace,livenessState,logbackAppenderHealthCheck,ping,readinessState
  ################################
  ### Spring server properties ###
  ################################
  server.port: 9240
  spring.jackson.serialization.write-dates-as-timestamps: false
  ### from application-common.yml ###
  server.shutdown: graceful
  server.servlet.encoding.charset: UTF-8
  server.servlet.encoding.enabled: true
  server.servlet.encoding.force: true
  server.compression.enabled: true
  server.compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/csv
  server.error.include-message: always
  spring.hateoas.use-hal-as-default-json-media-type: false
  # Force English on Spring Bean Validation error messages.
  spring.web.locale: en_EN
  spring.web.locale-resolver: fixed
  # By default, requests that don't match any controller are redirected to DefaultErrorController (/error) where
  # response is built with correct value of 404 as "status" but with "/error" as a "path" and
  # "No message available" as a "message". This configures DispatcherServlet to throw NoHandlerFoundException
  # when no controller matches the request which. The exception is subsequently handled by common global
  # exception handling mechanism.
  spring.mvc.throw-exception-if-no-handler-found: true
  # disable adding default resource handler mapping - it would break error responses when making request to nonexistent
  # endpoint
  spring.web.resources.add-mappings: false
  # configure Spring to automaticaly resolve x-fowarded headers
  server.forward-headers-strategy: framework
  ##################################
  ### Spring security properties ###
  ##################################
  spring.security.oauth2.resourceserver.jwt.issuer-uri: https://login.staging.clevermaps.io/oauth2/ausczk34l1H71WKiU0h7
logbackXml: |
  {{- tpl (.Files.Get "logback.xml") . }}
