nameOverride: can-docker-dwh-update-service
fullnameOverride: ""
namespace:
  name: can-docker-dwh-update-service
environment: staging
replicaCount: 0
timeToFinishWork: 3600
iam:
  role: arn:aws:iam::543777179833:role/eks-staging-can-{{ .Values.nameOverride }}-staging
service:
  type: ClusterIP
  health_port: 9151
image:
  repository: 543777179833.dkr.ecr.eu-west-1.amazonaws.com/can-docker-dwh-update-service
  tag: 1.0.0.911
  pullPolicy: Always
deployment:
  reloader: "true"
env:
  secrets:
    - name: SPRING_DATASOURCE_PASSWORD
      refname: '{{ .Release.Name }}'
      refkey: spring_datasource_password
  variables:
    - name: JAVA_OPTS
      value: -Xmx300m -Xms64m -XX:MaxMetaspaceSize=120m
volumeMounts:
  - mountPath: /etc/can/application.yml
    name: '{{ .Values.nameOverride }}'
    subPath: application.yml
  - mountPath: /etc/can/application.properties
    name: '{{ .Values.nameOverride }}'
    subPath: application.properties
  - mountPath: /etc/can/logback.xml
    name: '{{ .Values.nameOverride }}'
    subPath: logback.xml
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  enabled: false
applicationProperties:
  #######################################
  ### Application specific properties ###
  #######################################
  service.name: DwhUploadService
  ### AWS ###
  can.service:
    aws:
      accountId: "543777179833"
      region: eu-west-1
      stepFunctions:
        actions.workers:
          maxWorkerPoolSize: 2
    dwh.update.aws:
      stepFunctions:
        actions:
          dumpActivity: staging_dwh_dump_ttestt
          pullActivity: staging_dwh_pull_ttestt
          dropTableActivity: staging_dwh_drop_table_ttestt
      s3:
        dumpBucket: can-dwh-upload-dump-staging
        uploadBucket: can-dwh-upload-uploads-staging
  ### multi-tenant datasource properties ###
  can.db.datasource.urlPrefix: jdbc:postgresql://localhost:5432/
  can.db.datasource.urlPostfix: _dwh
  can.db.datasource.urlParams: loglevel=2
  can.db.pool.hikari.leakDetectionThreshold: 15000
  can.db.pool.hikari.minimumIdle: 2
  can.db.pool.hikari.idleTimeout: 20000
  can.db.pool.hikari.maximumPoolSize: 5
  # TODO: remove when CAN-13200 is released and deployed on production (BEGIN)
  ### Async AWS Step Functions ###
  can.service.dwh.states.dumpActivityArn: arn:aws:states:eu-west-1:543777179833:activity:staging_dwh_dump
  can.service.dwh.states.pullActivityArn: arn:aws:states:eu-west-1:543777179833:activity:staging_dwh_pull
  can.service.dwh.states.dropTableActivityArn: arn:aws:states:eu-west-1:543777179833:activity:staging_dwh_drop_table
  can.service.states.worker.maxWorkerPoolSize: 2
  # NOTE: following properties are relevant only when running in profile aws-step-functions-credentials (does not apply for staging/production deployment)
  #can.service.states.worker.accessKey: AWS_KEY
  #can.service.states.worker.secretKey: AWS_SECRET_KEY

  ### AWS S3 ###
  can.service.dwh.upload.bucket: can-dwh-upload-uploads-staging
  can.service.dwh.upload.bucket.region: eu-west-1
  # NOTE: following properties are relevant only when NOT running in profile aws-s3-iam-role-grant (does not apply for staging/production deployment)
  #can.service.dwh.upload.s3.accessKey: S3_KEY
  #can.service.dwh.upload.s3.secretKey: S3_ACCESS_KEY

  can.service.dwh.dump.bucket: can-dwh-upload-dump-staging
  can.service.dwh.dump.bucket.region: eu-west-1
  # NOTE: following properties are relevant only when NOT running in profile aws-s3-iam-role-grant (does not apply for staging/production deployment)
  #can.service.dwh.dump.s3.accessKey: S3_KEY
  #can.service.dwh.dump.s3.secretKey: S3_ACCESS_KEY
  # TODO: remove when CAN-13200 is released and deployed on production (END)

  can.service.dwh.dump.tmpdir: /tmp
  can.db.pool.fallbackDatabaseName: test
  # when editing, do not forget to change the dialect in JUnit test manually
  can.service.dwh.sqldialect: POSTGRES_9_5
  ### other microservices ###
  can.service.project.serverUrl: http://localhost:9060
  can.service.metadata.serverUrl: http://localhost:9040
  can.service.md.serverUrl: http://localhost:9130
  ##############################
  ### Spring core properties ###
  ##############################
  spring.profiles.active: dev
  #spring.profiles.active: dev, aws-credentials, aws-step-functions-actions
  #spring.profiles.active: aws-iam-role-grant, aws-step-functions-actions

  ### from application-common.yml ###
  spring.lifecycle.timeout-per-shutdown-phase: 60s
  ###########################
  ### Actuator properties ###
  ###########################
  management.server.port: 9151
  management.endpoint.health.group.readiness.include: db
  ### from application-common.yml ###
  management.server.add-application-context-header: false
  management.endpoint.metrics.enabled: true
  management.endpoint.prometheus.enabled: true
  management.endpoints.web.exposure.include: health,info,metrics,prometheus
  management.metrics.export.prometheus.enabled: true
  management.endpoint.health.show-details: always
  management.endpoint.health.probes.enabled: true
  management.endpoint.health.group.liveness.include: diskSpace,livenessState,logbackAppenderHealthCheck,ping,readinessState,pullWorkerHealthCheck,dumpWorkerHealthCheck,dropTableWorkerHealthCheck
  ################################
  ### Spring server properties ###
  ################################

  # do not start standard HTTP tomcat port
  server.port: -1
  ### from application-common.yml ###
  server.shutdown: graceful
  server.servlet.encoding.charset: UTF-8
  server.servlet.encoding.enabled: true
  server.servlet.encoding.force: true
  server.compression.enabled: true
  server.compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/csv
  server.error.include-message: always
  spring.hateoas.use-hal-as-default-json-media-type: false
  # Force English on Spring Bean Validation error messages.
  spring.web.locale: en_EN
  spring.web.locale-resolver: fixed
  # By default, requests that don't match any controller are redirected to DefaultErrorController (/error) where
  # response is built with correct value of 404 as "status" but with "/error" as a "path" and
  # "No message available" as a "message". This configures DispatcherServlet to throw NoHandlerFoundException
  # when no controller matches the request which. The exception is subsequently handled by common global
  # exception handling mechanism.
  spring.mvc.throw-exception-if-no-handler-found: true
  # disable adding default resource handler mapping - it would break error responses when making request to nonexistent
  # endpoint
  spring.web.resources.add-mappings: false
  # configure Spring to automaticaly resolve x-fowarded headers
  server.forward-headers-strategy: framework
  ##################################
  ### Spring security properties ###
  ##################################
  spring.security.oauth2.resourceserver.jwt.issuer-uri: https://login.staging.clevermaps.io/oauth2/ausczk34l1H71WKiU0h7
  ##############################
  ### Spring data properties ###
  ##############################
  # special datasources using standard Postgres JDBC driver
  # it supports CopyManager used for data loads
  spring.datasource.driverClassName: org.postgresql.Driver
  spring.datasource.username: dwh
  spring.datasource.password: testtest
  ########################################
  ### Spring data migration properties ###
  ########################################
  spring.liquibase.enabled: false
logbackXml: |
  {{- tpl (.Files.Get "logback.xml") . }}
