nameOverride: can-docker-export-service
fullnameOverride: ""
namespace:
  name: can-docker-export-service
environment: staging
replicaCount: 1
timeToFinishWork: 3600
iam:
  role: arn:aws:iam::543777179833:role/eks-staging-can-can-docker-export-service-staging
service:
  type: ClusterIP
  port: 9120
  health_port: 9121
image:
  repository: 543777179833.dkr.ecr.eu-west-1.amazonaws.com/can-docker-export-service
  tag: 1.0.0.913
  pullPolicy: Always
deployment:
  reloader: "true"
env:
  variables:
    - name: JAVA_OPTS
      value: -Xmx220m -Xms32m -XX:MaxMetaspaceSize=120m
volumeMounts:
  - mountPath: /etc/can/application.yml
    name: '{{ .Values.nameOverride }}'
    subPath: application.yml
  - mountPath: /etc/can/application.properties
    name: '{{ .Values.nameOverride }}'
    subPath: application.properties
  - mountPath: /etc/can/logback.xml
    name: '{{ .Values.nameOverride }}'
    subPath: logback.xml
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  paths:
    - /rest/projects/([a-z0-9]{16})/export(.*)
  hosts:
    - staging.clevermaps.io
  tls: []
applicationProperties:
  #######################################
  ### Application specific properties ###
  #######################################
  service.name: ExportService
  ### AWS ###
  can.service:
    aws:
      accountId: "543777179833"
      region: eu-west-1
      stepFunctions:
        actions.workers:
          maxWorkerPoolSize: 2
    export.aws:
      stepFunctions:
        actions:
          exportActivity: staging_export
      s3:
        exportBucket: can-export-staging
  # TODO: remove when CAN-13200 is released and deployed on production (BEGIN)
  ### Async AWS Step Functions ###
  can.service.export.states.exportActivityArn: arn:aws:states:eu-west-1:543777179833:activity:staging_export
  can.service.states.worker.maxWorkerPoolSize: 2
  # NOTE: following properties are relevant only when running in profile aws-step-functions-credentials (does not apply for staging/production deployment)
  #can.service.states.worker.accessKey: AWS_KEY
  #can.service.states.worker.secretKey: AWS_SECRET_KEY

  ### AWS S3 ###
  can.service.export.bucket: can-export-staging
  can.service.export.bucket.region: eu-west-1
  # NOTE: following properties are relevant only when NOT running in profile aws-s3-iam-role-grant (does not apply for staging/production deployment)
  #can.service.export.s3.accessKey: AWS_KEY
  #can.service.export.s3.secretKey: AWS_SECRET_KEY
  # TODO: remove when CAN-13200 is released and deployed on production (END)

  can.service.export.tmpdir: /tmp
  can.service.export.dwh.pagesize: 2000
  ### other microservices ###
  can.service.project.serverUrl: https://staging.clevermaps.io
  can.service.md.serverUrl: https://staging.clevermaps.io
  can.service.dwh.serverUrl: https://staging.clevermaps.io
  ##############################
  ### Spring core properties ###
  ##############################
  spring.profiles.active: dev
  #spring.profiles.active: dev, aws-credentials, aws-step-functions-actions
  #spring.profiles.active: aws-iam-role-grant, aws-step-functions-actions

  ### from application-common.yml ###
  spring.lifecycle.timeout-per-shutdown-phase: 60s
  ###########################
  ### Actuator properties ###
  ###########################
  management.server.port: 9121
  ### from application-common.yml ###
  management.server.add-application-context-header: false
  management.endpoint.metrics.enabled: true
  management.endpoint.prometheus.enabled: true
  management.endpoints.web.exposure.include: health,info,metrics,prometheus
  management.metrics.export.prometheus.enabled: true
  management.endpoint.health.show-details: always
  management.endpoint.health.probes.enabled: true
  management.endpoint.health.group.liveness.include: diskSpace,livenessState,logbackAppenderHealthCheck,ping,readinessState,exportWorkerHealthCheck
  ################################
  ### Spring server properties ###
  ################################
  server.port: 9120
  ### from application-common.yml ###
  server.shutdown: graceful
  server.servlet.encoding.charset: UTF-8
  server.servlet.encoding.enabled: true
  server.servlet.encoding.force: true
  server.compression.enabled: true
  server.compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/csv
  server.error.include-message: always
  spring.hateoas.use-hal-as-default-json-media-type: false
  spring.web.locale: en_EN
  spring.web.locale-resolver: fixed
  spring.mvc.throw-exception-if-no-handler-found: true
  spring.web.resources.add-mappings: false
  # configure Spring to automaticaly resolve x-fowarded headers
  server.forward-headers-strategy: framework
  ##################################
  ### Spring security properties ###
  ##################################
  spring.security.oauth2.resourceserver.jwt.issuer-uri: https://login.staging.clevermaps.io/oauth2/ausczk34l1H71WKiU0h7
logbackXml: |
  {{- tpl (.Files.Get "logback.xml") . }}
