nameOverride: can-docker-auditlog-service
fullnameOverride: ""
namespace:
  name: can-docker-auditlog-service
environment: staging
replicaCount: 1
timeToFinishWork: 3600
iam:
  role: arn:aws:iam::812131102444:role/eks-staging-can-{{ .Values.nameOverride }}-staging
service:
  type: ClusterIP
  port: 9070
  health_port: 9071
image:
  repository: 543777179833.dkr.ecr.eu-west-1.amazonaws.com/can-docker-auditlog-service
  tag: 1.0.0.45
  pullPolicy: Always
deployment:
  reloader: "true"
env:
  variables:
    - name: JAVA_OPTS
      value: -Xmx128m -Xms32m -XX:MaxMetaspaceSize=120m
volumeMounts:
  - mountPath: /etc/can/application.yml
    name: '{{ .Values.nameOverride }}'
    subPath: application.yml
  - mountPath: /etc/can/application.properties
    name: '{{ .Values.nameOverride }}'
    subPath: application.properties
  - mountPath: /etc/can/logback.xml
    name: '{{ .Values.nameOverride }}'
    subPath: logback.xml
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  paths:
    - /rest/auditlog(.*)
  hosts:
    - staging.cleveranalytics.com
  tls: []
applicationProperties:
  #######################################
  ### Application specific properties ###
  #######################################
  service.name: can-auditlog-service
  ### Async AWS Step Functions ###
  can.service.auditlog.states.logStepFunctionResultActivityArn: arn:aws:states:eu-west-1:812131102444:activity:staging_log_step_function_result
  can.service.auditlog.worker.maxWorkerPoolSize: 2
  ### DynamoDB common lib configuration (active only with profile: aws-dynamodb) ###
  can.service.dynamodb:
    region: eu-west-1
    # timeout in milliseconds for a single http request to complete
    apiCallAttemptTimeout: 5000
    # timeout in milliseconds for DynamoDbClient to complete the execution of an API call - a single API call that reads
    # at most 1MB of data from DynamoDb (before applying filter condition) - may be multiple http requests (e.g. retries
    # when apiCallAttemptTimeout for a single http request is exceeded)
    apiCallTimeout: 10000
    # limit in milliseconds for audit log service to complete querying data from DynamoDb - all API calls including
    # subsequent API calls using lastEvaluatedKey from previous responses when 1MB data limit was hit
    queryTimeLimit: 30000
    # when caching table descriptions is turned on information about table key schema and indices needed for extracting
    # last evaluated key is fetched only once per table name
    cacheTableDescriptions: true
  ### DynamoDB audit-log-service specific configuration
  can.service.auditlog.dynamodb:
    environment: staging
    auditLogTable: staging_audit_log
    auditLogTable.projectIdIndex: project_id_index
    jobsHistoryTable: staging_jobs_history
    usageTable: staging_usage
    lastUsageTable: staging_last_usage
  ### other microservices ###
  can.service.project.serverUrl: https://staging.clevermaps.io:443
  ###################################
  ### Spring cloud AWS properties ###
  ###################################
  cloud.aws.region.static: eu-west-1
  ######################################
  ### Spring cloud stream properties ###
  ######################################
  spring.cloud:
    function:
      definition: consumeAuditLogKinesisPersistToAuditLogDynamoDb;consumeAuditLogDynamoDbPersistToJobsHistoryDynamoDb;consumeAuditLogDynamoDbPersistProjectSizeMetricsToUsageAndLastUsageDynamoDb;consumeAuditLogDynamoDbComputeExecutionMetricsToUsageDynamoDb
    stream:
      bindings:
        consumeAuditLogKinesisPersistToAuditLogDynamoDb-in-0:
          destination: staging_audit_log_kinesis
          group: persist_to_audit_log_dynamodb
          consumer:
            useNativeDecoding: true
        consumeAuditLogDynamoDbPersistToJobsHistoryDynamoDb-in-0:
          destination: staging_audit_log
          group: persist_to_jobs_history_dynamodb
          consumer:
            useNativeDecoding: true
        consumeAuditLogDynamoDbPersistProjectSizeMetricsToUsageAndLastUsageDynamoDb-in-0:
          destination: staging_audit_log
          group: persist_project_size_metrics_to_usage_and_last_usage_dynamodb
          consumer:
            useNativeDecoding: true
        consumeAuditLogDynamoDbComputeExecutionMetricsToUsageDynamoDb-in-0:
          destination: staging_audit_log
          group: compute_execution_metrics_to_usage_dynamodb
          consumer:
            useNativeDecoding: true
      kinesis:
        binder:
          autoCreateStream: false
          checkpoint:
            table: spring_integration_metadata_store
          locks:
            table: spring_integration_lock_registry
        bindings:
          consumeAuditLogKinesisPersistToAuditLogDynamoDb-in-0:
            consumer:
              listenerMode: batch
          consumeAuditLogDynamoDbPersistToJobsHistoryDynamoDb-in-0:
            consumer:
              listener-mode: batch
              dynamo-db-streams: true
          consumeAuditLogDynamoDbPersistProjectSizeMetricsToUsageAndLastUsageDynamoDb-in-0:
            consumer:
              listener-mode: batch
              dynamo-db-streams: true
          consumeAuditLogDynamoDbComputeExecutionMetricsToUsageDynamoDb-in-0:
            consumer:
              listener-mode: batch
              dynamo-db-streams: true
  ##############################
  ### Spring core properties ###
  ##############################

  # NOTE: AWS DynamoDB Activities are polled only with profile:
  # aws-dynamodb
  # if set "aws-dynamodb-credentials" profile,
  # the properties can.service.auditlog.dynamodb.accessKey and secretKey
  # are used for setting credentials
  # if set "aws-dynamodb-iam-role-grant" the IAM role is used instead
  # Step function is active only with profiles:
  # aws-step-functions, aws-step-functions-credentials or aws-step-functions-iam-role-grant
  # Kinesis is active only with profiles:
  # aws-kinesis, aws-kinesis-credentials or aws-kinesis-iam-role-grant
  # aws-localstack profile is used when developing locally with LocalStack
  spring.profiles.active: aws-dynamodb,aws-dynamodb-credentials,aws-step-functions,aws-step-functions-credentials
  #spring.profiles.active: aws-dynamodb,aws-dynamodb-credentials,aws-step-functions,aws-step-functions-credentials,aws-kinesis,aws-kinesis-credentials
  #spring.profiles.active: aws-dynamodb,aws-dynamodb-credentials,aws-kinesis,aws-kinesis-credentials
  #spring.profiles.active: aws-dynamodb,aws-dynamodb-iam-role-grant,aws-step-functions,aws-step-functions-iam-role-grant,aws-kinesis,aws-kinesis-iam-role-grant

  ### from application-common.yml ###
  spring.lifecycle.timeout-per-shutdown-phase: 60s
  ###########################
  ### Actuator properties ###
  ###########################
  management.server.port: 9071
  management.endpoint.health.group.readiness.include: dynamoDb
  ### from application-common.yml ###
  management.server.add-application-context-header: false
  management.endpoint.metrics.enabled: true
  management.endpoint.prometheus.enabled: true
  management.endpoints.web.exposure.include: health,info,metrics,prometheus
  management.metrics.export.prometheus.enabled: true
  management.endpoint.health.show-details: always
  management.endpoint.health.probes.enabled: true
  management.endpoint.health.group.liveness.include: diskSpace,livenessState,logbackAppenderHealthCheck,ping,readinessState
  ################################
  ### Spring server properties ###
  ################################
  server.port: 9070
  ### from application-common.yml ###
  server.shutdown: graceful
  server.servlet.encoding.charset: UTF-8
  server.servlet.encoding.enabled: true
  server.servlet.encoding.force: true
  server.compression.enabled: true
  server.compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/csv
  server.error.include-message: always
  spring.hateoas.use-hal-as-default-json-media-type: false
  # Force English on Spring Bean Validation error messages.
  spring.web.locale: en_EN
  spring.web.locale-resolver: fixed
  # By default, requests that don't match any controller are redirected to DefaultErrorController (/error) where
  # response is built with correct value of 404 as "status" but with "/error" as a "path" and
  # "No message available" as a "message". This configures DispatcherServlet to throw NoHandlerFoundException
  # when no controller matches the request which. The exception is subsequently handled by common global
  # exception handling mechanism.
  spring.mvc.throw-exception-if-no-handler-found: true
  # disable adding default resource handler mapping - it would break error responses when making request to nonexistent
  # endpoint
  spring.web.resources.add-mappings: false
  # configure Spring to automaticaly resolve x-fowarded headers
  server.forward-headers-strategy: framework
  ##################################
  ### Spring security properties ###
  ##################################
  spring.security.oauth2.resourceserver.jwt.issuer-uri: https://login.staging.clevermaps.io/oauth2/ausczk34l1H71WKiU0h7
logbackXml: |
  {{- tpl (.Files.Get "logback.xml") . }}
